# Generated by Django 4.2.8 on 2024-07-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="bic",
            field=models.CharField(default="XXXXXXXXXXX", max_length=11),
        ),
        migrations.AddField(
            model_name="invoice",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="invoice",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="iban",
            field=models.CharField(
                default="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", max_length=34
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="postal_code",
            field=models.CharField(default="00000", max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="siren",
            field=models.CharField(default="000000000", max_length=9),
        ),
    ]
