# Generated by Django 4.2.8 on 2024-07-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_invoice_address_invoice_bic_invoice_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="items",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="InvoiceItem",
        ),
    ]
