# Generated by Django 4.2.8 on 2024-07-29 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user_bic_user_city_user_postal_code_user_siren"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="id",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="id",
        ),
        migrations.AddField(
            model_name="invoice",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
