# Generated by Django 4.2.8 on 2024-08-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_invoice_items_delete_invoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
