# Generated by Django 4.2.8 on 2024-07-22 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_user_address_user_first_name_user_iban_user_login_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=255)),
                ("client_name", models.CharField(max_length=255)),
                ("client_address", models.CharField(max_length=255)),
                ("client_postal_code", models.CharField(max_length=10)),
                ("client_city", models.CharField(max_length=100)),
                ("tva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_ht", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_tva", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_ttc", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="main.invoice",
                    ),
                ),
            ],
        ),
    ]
