# Generated by Django 4.2.8 on 2024-07-22 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_invoice_invoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
